#SERVER
server.port=8088

# DATABASE (MariaDB)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# ACTUATOR
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# ROBUSTNESS (RFC 7807)
spring.mvc.problem-details.enabled=true

# LOGGING (JSON Ready for Prod - Console for Dev)
logging.level.org.springframework.web=INFO
logging.level.org.flywaydb=INFO
